InterviewGenerator/routes.py
from flask import Blueprint
from flask import Flask, g, request, render_template, flash, redirect, url_for,session, logging, send_file, jsonify, make_response
from flask_login import login_required, logout_user, current_user, login_user
from functools import wraps
import jwt
import datetime

from forms import QuestionsCreateForm, QuestionSetCreateForm, LoginForm, AddUserForm, SignupForm
from models import db, Question, QuestionSet, QuestionsSets, User, Interview, QuestionMark
helper = Blueprint('helper', __name__)

SECRET_KEY = b'murmurmur'


def token_required(f):
    @wraps(f)
    def decorator(*args, **kwargs):
        token = None
        if request.args.get('token'):
            token = request.args.get('token')

        if not token:
            return jsonify({'message': 'a valid token is missing'})
        try:
            data = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
        except:
            return jsonify({'message': 'token is invalid'})

        return f(token, *args, **kwargs)

    return decorator


def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_admin == False:
            flash("You are not allowed to view this page since you're not admin")
            return redirect(url_for('helper.dashboard'))
        return f(*args, **kwargs)
    return decorated_function


def recruiter_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if (current_user.is_recruiter == False) and (current_user.is_admin == False):
            flash("You are not allowed to view this page since you're not recruiter")
            return redirect(url_for('helper.dashboard'))
        return f(*args, **kwargs)
    return decorated_function


def expert_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if (current_user.is_expert == False) and (current_user.is_admin == False):
            flash("You are not allowed to view this page since you're not expert")
            return redirect(url_for('helper.dashboard'))
        return f(*args, **kwargs)
    return decorated_function


@helper.route('/')
@helper.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')


@helper.route('/questions/all', methods=['GET', 'POST'])
@login_required
def show_questions():
    questions = Question.query.all()
    sets = QuestionSet.query.all()
    sets_themes = dict()
    for s in QuestionSet.query.all():
        set_q = s.questions
        themes = []
        for q in set_q:
            themes.append(q.theme)
        themes = list(set(themes))
        sets_themes[str(s.id)] = themes
    return render_template('all_questions.html', questions=questions, sets=sets, sets_themes=sets_themes)


@helper.route('/questions/all/full', methods=['GET', 'POST'])
@login_required
def show_questions_full():
    themes = []
    for theme in Question.query.with_entities(Question.theme).distinct().all():
        themes.extend(theme)
    if request.method == 'POST':
        selected_theme = request.form['theme']
        selected_mark = request.form['mark']

        if selected_theme and selected_mark:
            questions = Question.query.with_entities(Question.id).filter(Question.theme == selected_theme, Question.mark == selected_mark).all()
            return jsonify({'redirect': url_for('helper.show_questions_full', themes=themes, questions=questions, selected_theme=selected_theme, selected_mark=selected_mark)})
        elif selected_theme:
            questions = Question.query.with_entities(Question.id).filter(Question.theme == selected_theme).all()
            return jsonify({'redirect': url_for('helper.show_questions_full', themes=themes, questions=questions,
                                    selected_theme=selected_theme)})
        elif selected_mark:
            questions = Question.query.with_entities(Question.id).filter(Question.mark == selected_mark).all()
            return jsonify({'redirect': url_for('helper.show_questions_full', themes=themes, questions=questions,
                                                selected_mark=selected_mark)})
    data = request.args
    if data:
        selected_theme = request.args.getlist('selected_theme')
        selected_mark = request.args.getlist('selected_mark')
        questions = request.args.getlist('questions')
        ids = [s.replace('(', '').replace(')', '').replace(',', '') for s in questions]
        themes = request.args.getlist('themes')
        questions = Question.query.filter(Question.id.in_(ids)).all()
        if selected_theme and selected_mark:
            selected_theme = selected_theme[0]
            selected_mark = selected_mark[0]
            return render_template('all_questions_full.html', themes=themes, questions=questions, selected_theme=selected_theme, selected_mark=selected_mark)
        elif selected_theme:
            selected_theme = selected_theme[0]
            return render_template('all_questions_full.html', themes=themes, questions=questions,
                                   selected_theme=selected_theme)
        elif selected_mark:
            selected_mark = selected_mark[0]
            return render_template('all_questions_full.html', themes=themes, questions=questions,
                                   selected_mark=selected_mark)
    questions = Question.query.all()
    return render_template('all_questions_full.html', themes=themes, questions=questions)


@helper.route('/create_question', methods=['GET', 'POST'])
@login_required
@expert_required
def create_question():
    form = QuestionsCreateForm(request.form)
    if request.method == 'POST':
        if form.validate():
            theme = form.theme.data
            essence = form.essence.data
            answer = form.answer.data
            mark = form.mark.data
            question = Question(theme, essence, answer, mark)
            db.session.add(question)
            db.session.commit()
            return redirect('/questions/all/full')
    return render_template('create_question.html', form=form)


@helper.route('/questions/all/<int:id>/update', methods=['GET', 'POST'])
@login_required
@expert_required
def update_question(id):
    form = QuestionsCreateForm(request.form)
    question = Question.query.filter_by(id=id).first()
    if request.method == 'POST':
        if form.validate():
            theme = form.theme.data
            essence = form.essence.data
            answer = form.answer.data
            mark = form.mark.data
            question = Question.query.filter_by(id=id).first()
            question.theme = theme
            question.essence = essence
            question.answer = answer
            old_mark = question.mark
            question.mark = mark

            scores_w_q = QuestionMark.query.filter_by(question_id=question.id).all()
            for s in scores_w_q:
                i = Interview.query.filter_by(id=s.interview_id).first()
                if i.max_score:
                    i.max_score = i.max_score - old_mark + mark
                    obj_s = s
                    obj_mark = s.mark
                    obj_s.mark = round((s.mark*mark)/old_mark)
                    i.score = i.score - obj_mark + obj_s.mark
                    db.session.commit()
            db.session.commit()
            return redirect('/questions/all/full')
    return render_template('update_question.html', form=form, question=question)


@helper.route('/questions/all/<int:id>/delete', methods=['GET', 'POST'])
@login_required
@expert_required
def delete_question(id):
    question = Question.query.filter_by(id=id).first()
    if request.method == 'POST':
        if question:
            delete_m = QuestionMark.__table__.delete().where(QuestionMark.question_id == id)
            db.session.execute(delete_m)
            db.session.commit()
            db.session.delete(question)
            db.session.commit()
            flash('Delete was successfull')
            return redirect('/questions/all/full')
        flash('Unable to delete')

    return render_template('delete.html')


@helper.route('/sets/all/full', methods=['GET', 'POST'])
@login_required
def show_sets_full():
    levels = []
    for level in QuestionSet.query.with_entities(QuestionSet.level).distinct().all():
        levels.extend(level)

    selected_level = request.args.get('level')

    if selected_level:
        sets = QuestionSet.query.filter(QuestionSet.level == selected_level).all()
        return render_template('all_sets_full.html', levels=levels, sets=sets, selected_level=selected_level)
    else:
        selected_level = request.args.get('selected_level', None, type=str)
        if selected_level:
            sets = QuestionSet.query.filter(QuestionSet.level == selected_level).all()
            return render_template('all_sets_full.html', levels=levels, sets=sets,
                                   selected_level=selected_level)
    sets = QuestionSet.query.all()

    return render_template('all_sets_full.html', levels=levels, sets=sets)


@helper.route('/create_question_set')
@login_required
def create_set():
    form = QuestionSetCreateForm(request.form)
    form.questions.query = db.session.query(Question).order_by(Question.essence)
    questions = Question.query.all()
    return render_template('create_set.html', form=form, questions=questions)


@helper.route("/add_set", methods=["GET", "POST"])
@login_required
@expert_required
def add_set():
    if request.method == 'POST':
        name = request.form['name']
        level = request.form['level']
        questions_id = request.form['hidden_questions']
        questions_id = list(questions_id.split(","))
        questions = [Question.query.filter_by(id=ex_id).first() for ex_id in questions_id]
        set = QuestionSet(name=name, questions=questions, level=level)
        db.session.add(set)
        db.session.commit()
        msg = 'New record created successfully'
    return jsonify("OK")

InterviewGenerator/templates/add_to_interview.html
{% extends 'layout.html' %}
{% block head %}
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="/static/common.css">
  <link rel="stylesheet" href="/static/create_interview.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
{% endblock %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div id="heading">
  <div class="col">
    <h1>Add Questions</h1>
  </div>
</div>
<div class="login-box well">
  <form method="POST" enctype="multipart/form-data" id="multiple_select_form">
    Sets
    <div class="form-group">
    <select name="sets" id="sets" class="form-control selectpicker-s" data-live-search="true" multiple>
      {% for set in sets %}
      <option value="{{set.id}}">{{set}}</option>
      {% endfor %}
    </select>
    </div>
    <br /><br />
    <div class="form-group">
    <input type="hidden" name="hidden_sets" id="hidden_sets" />
      <div class="form-group">
    Questions
    <select name="questions" id="questions" class="form-control selectpicker-q" data-live-search="true" multiple>
      {% for question in questions %}
      <option value="{{question.id}}">{{question}}</option>
      {% endfor %}
    </select>
    </div>
    <br /><br />
    <input type="hidden" name="hidden_questions" id="hidden_questions" />
    <p><input type="submit" name="submit" class="btn btn-primary" value="Submit" /></p>
  </form>
</div>
<script>
$(document).ready(function(){
    $('.selectpicker-s').selectpicker();
    $('.selectpicker-q').selectpicker();
    $('.selectpicker-q').selectpicker('val', {{ questions_id }});
    $('.selectpicker-q').selectpicker('refresh');
    $('.selectpicker-s').selectpicker('val', {{ sets_id }});
    $('.selectpicker-s').selectpicker('refresh');
    $('#hidden_questions').val({{ questions_id }})
    $('#hidden_sets').val({{ sets_id }})

    $('#sets').change(function(){
      $('#hidden_sets').val($('#sets').val());
    });

    $('#questions').change(function(){
      $('#hidden_questions').val($('#questions').val());
    });

    $('#multiple_select_form').on('submit', function(event){
        event.preventDefault();
            var form_data = $(this).serialize();
            $.ajax({
                url:"/ajax_interview_add_questions/" + {{ interview.id }},
                method:"POST",
                data:form_data,
                success:function(data)
                {
                window.location.href = "/interviews";
                }
            })
    });
});
</script>
{% endblock %}

InterviewGenerator/templates/all_questions.html
{% extends 'layout.html' %}

{% block head %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/jquery.simplePagination.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/simplePagination.min.css">
	<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='disp.css') }}">
{% endblock %}

{% block body %}
<table class="center">
<td style="vertical-align:top;">
<div class="box box--list" style="position : fixed; left: 50%">
	<header class="box--list__header">
		<h1 class="box--list__header-title">Sets</h1>
		<a href="{{ url_for('helper.show_sets_full') }}" class="box--list__header-link">
			View all
			<svg xmlns="http://www.w3.org/2000/svg" width="10.444" height="9.7"><defs><clipPath id="a"><path fill="none" d="M0 0h10.444v9.7H0z"/></clipPath></defs><g fill="none" stroke="#2a46cc" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.438" clip-path="url(#a)"><path d="M.719 4.85h8.709M5.594 8.683L9.427 4.85M5.594 1.017L9.427 4.85"/></g></svg>
		</a>
	</header>

	<input type="text" class="live-search-box-s" placeholder="search here" />
	<div class="box--list__items live-search-s" >
		{% for set in sets %}
		<div class="box--list__item" id="{{ set.id }}" draggable="true" ondragstart="drag(event)">
			<h2 class="box--list__title">{{ set.name }}</h2>
			<span class="tag tag-primary">{{ set.level }}</span>
		</div>
		{% endfor %}
	</div>
	<div id="pagination-s" data-percent="{{ sets|length }}"></div>
</div>

</td>
<td style="vertical-align:top;">

<div class="box box--list right">
	<header class="box--list__header">
		<h1 class="box--list__header-title">Questions</h1>
		<a href="{{ url_for('helper.show_questions_full') }}" class="box--list__header-link">
			View all
			<svg xmlns="http://www.w3.org/2000/svg" width="10.444" height="9.7"><defs><clipPath id="a"><path fill="none" d="M0 0h10.444v9.7H0z"/></clipPath></defs><g fill="none" stroke="#2a46cc" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.438" clip-path="url(#a)"><path d="M.719 4.85h8.709M5.594 8.683L9.427 4.85M5.594 1.017L9.427 4.85"/></g></svg>
		</a>
	</header>

	<input type="text" class="live-search-box-q" placeholder="search here" />
	<div class="box--list__items live-search-q" >
		{% for question in questions %}
		<div class="box--list__item" id="{{ question.id }}" draggable="true" ondragstart="drag(event)">
			<h2 class="box--list__title">{{ question.essence }}</h2>
			<span class="tag tag-primary">{{ question.theme }}</span>
		</div>
		{% endfor %}
	</div>
	<div id="pagination-q" data-percent="{{ questions|length }}"></div>
  <script type="text/javascript">
	jQuery(document).ready(function($){

	$('.live-search-q .box--list__item').each(function(){
	$(this).attr('data-search-term', $(this).text().toLowerCase());
	});

	$('.live-search-box-q').on('keyup', function(){

	var searchTerm = $(this).val().toLowerCase();
	var state = [];
    if ($(this).val() != '') {

		$('.live-search-q .box--list__item').each(function(){
              if ($(this).filter('[data-search-term *= ' + searchTerm + ']').length > 0 || searchTerm.length < 1) {
                  $(this).show();
                  $(this).addClass("search");
              } else {
                  $(this).hide();
                  $(this).removeClass("search");
              }
		});
		console.log(state);
		$(".live-search-q .box--list__item.search").slice(4).hide();
        $('#pagination-q').pagination({
            items: $(".live-search-q .box--list__item.search").length,
            itemsOnPage: 4,
            onPageClick: function (noofele) {
                $('.live-search-q .box--list__item.search').hide()
                    .slice(4*(noofele-1),
                    4+ 4* (noofele - 1)).show();
            }
        });

    } else {
        $('.live-search-q .box--list__item').each(function(){
              $(this).show();
		});
        $(".live-search-q .box--list__item").slice(4).hide();
        $('#pagination-q').show()
        $('#pagination-q').pagination({

            items: $(".live-search-q .box--list__item").length,
            itemsOnPage: 4,
            onPageClick: function (noofele) {
                $(".live-search-q .box--list__item").hide()
                    .slice(4*(noofele-1),
                    4+ 4* (noofele - 1)).show();
            }
        });
    }
	});

	$(".live-search-q .box--list__item").slice(4).hide();
        $('#pagination-q').pagination({

            items: $(".live-search-q .box--list__item").length,
            itemsOnPage: 4,
            onPageClick: function (noofele) {
                $(".live-search-q .box--list__item").hide()
                    .slice(4*(noofele-1),
                    4+ 4* (noofele - 1)).show();
            }
        });


	$('.live-search-s .box--list__item').each(function(){
	$(this).attr('data-search-term', $(this).text().toLowerCase());
	});

	$('.live-search-box-s').on('keyup', function(){

	var searchTerm = $(this).val().toLowerCase();
	var state = [];
    if ($(this).val() != '') {

		$('.live-search-s .box--list__item').each(function(){
              if ($(this).filter('[data-search-term *= ' + searchTerm + ']').length > 0 || searchTerm.length < 1) {
                  $(this).show();
                  $(this).addClass("search");
              } else {
                  $(this).hide();
                  $(this).removeClass("search");
              }
		});
		console.log(state);
		$(".live-search-s .box--list__item.search").slice(3).hide();
        $('#pagination-s').pagination({
            items: $(".live-search-s .box--list__item.search").length,
            itemsOnPage: 3,
            onPageClick: function (noofele) {
                $('.live-search-s .box--list__item.search').hide()
                    .slice(3*(noofele-1),
                    3+ 3* (noofele - 1)).show();
            }
        });

    } else {
        $('.live-search-s .box--list__item').each(function(){
              $(this).show();
		});
        $(".live-search-s .box--list__item").slice(3).hide();
        $('#pagination-s').show()
        $('#pagination-s').pagination({

            items: $(".live-search-s .box--list__item").length,
            itemsOnPage: 3,
            onPageClick: function (noofele) {
                $(".live-search-s .box--list__item").hide()
                    .slice(3*(noofele-1),
                    3+ 3* (noofele - 1)).show();
            }
        });
    }
	});

	$(".live-search-s .box--list__item").slice(3).hide();
        $('#pagination-s').pagination({

            items: $(".live-search-s .box--list__item").length,
            itemsOnPage: 3,
            onPageClick: function (noofele) {
                $(".live-search-s .box--list__item").hide()
                    .slice(3*(noofele-1),
                    3+ 3* (noofele - 1)).show();
            }
        });

	});
	</script>
</div>
</td>
</table>

{% endblock %}

InterviewGenerator/templates/create_interview.html
{% extends 'layout.html' %}
{% block head %}
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="/static/common.css">
  <link rel="stylesheet" href="/static/create_interview.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
{% endblock %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div id="heading">
  <div class="col">
    <h1>Create Interview</h1>
  </div>
</div>
<div class="login-box well">
  <form method="POST" enctype="multipart/form-data" id="multiple_select_form">
    Assignee
    <div class="form-group">
      <input name="assignee" type="text" class="form-control" required/>
    </div>
    Position
    <div class="form-group">
      <input name="position" type="text" class="form-control" required/>
    </div>
    Experts
    <div class="form-group">
    <select name="experts" id="experts" class="form-control selectpicker" data-live-search="true" multiple required>
      {% for expert in experts %}
      <option value="{{expert.id}}">{{expert}}</option>
      {% endfor %}
    </select>
    </div>
    <br /><br />
    <div class="form-group">
    <input type="hidden" name="hidden_experts" id="hidden_experts" />
    <p><input type="submit" name="submit" class="btn btn-primary" value="Submit" /></p>
  </form>
</div>
<script>
$(document).ready(function(){
    $('.selectpicker').selectpicker();

    $('#experts').change(function(){
      $('#hidden_experts').val($('#experts').val());
    });

    $('#multiple_select_form').on('submit', function(event){
        event.preventDefault();
        if($('#experts').val() != '')
        {
            var form_data = $(this).serialize();
            $.ajax({
                url:"/add_interview",
                method:"POST",
                data:form_data,
                success:function(data)
                {
                window.location.href = "/dashboard";
                }
            })
        }
        else
        {
            alert("Please select framework");
            return false;
        }
    });
});
</script>
{% endblock %}

InterviewGenerator/templates/create_question.html
{% extends 'layout.html' %}
{% block head %}
  <link rel="stylesheet" href="/static/create_interview.css">
{% endblock %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div id="heading">
  <div class="col">
    <h1>Create Question</h1>
  </div>
</div>
<div class="login-box well">
  <form method="POST" action={{url_for('helper.create_question')}} enctype="multipart/form-data">
    <div class="form-group">
      {{ render_field(form.theme, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.essence, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.answer, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.mark, class="form-control") }}
    </div>
    <p><input type="submit" class="btn btn-primary" value="Submit"></p>
  </form>
</div>
{% endblock %}

InterviewGenerator/templates/create_set.html
{% extends 'layout.html' %}
{% block head %}
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="/static/create_interview.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
{% endblock %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div id="heading">
  <div class="col">
    <h1>Create Set</h1>
  </div>
</div>
<div class="login-box well">
  <form method="POST" enctype="multipart/form-data" id="multiple_select_form">
    <div class="form-group">
      {{ render_field(form.name, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.questions, class="form-control selectpicker questions", data_live_search="true") }}
    </div>
    <div class="form-group">
      {{ render_field(form.level, class="form-control") }}
    </div>
    <input type="hidden" name="hidden_questions" id="hidden_questions" />
    <p><input type="submit" class="btn btn-primary" value="Submit"></p>
  </form>
</div>
<script>
$(document).ready(function(){
    console.log("Script works");
    $('.selectpicker').selectpicker();

    $('#questions').change(function(){
      $('#hidden_questions').val($('#questions').val());
    });

    $('#multiple_select_form').on('submit', function(event){
        event.preventDefault();
        if($('#questions').val() != '')
        {
            var form_data = $(this).serialize();
            console.log(form_data);
            $.ajax({
                url:"/add_set",
                method:"POST",
                data:form_data,
                success:function(data)
                {
                window.location.href = "/sets/all/full";
                }
            })
        }
        else
        {
            alert("Please select framework");
            return false;
        }
    });
});
</script>
{% endblock %}

InterviewGenerator/templates/create_user.html
{% extends 'layout.html' %}
{% block head %}
  <link rel="stylesheet" href="/static/create_interview.css">
{% endblock %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div id="heading">
  <div class="col">
    <h1>Add user</h1>
  </div>
</div>
<div class="login-box well">
  <form method="POST" action={{url_for('helper.add_user')}} enctype="multipart/form-data">
    <div class="form-group">
      {{ render_field(form.name, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.surname, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.email, class="form-control") }}
    </div>
    <div class="form-group">
      {{ render_field(form.role) }}
    </div>
    <p><input type="submit" class="btn btn-primary" value="Submit"></p>
  </form>
</div>
{% endblock %}

InterviewGenerator/templates/delete_set.html
{% extends 'layout.html' %}
{% block head %}
  <link rel="stylesheet" href="/static/common.css">
  <link rel="stylesheet" href="/static/create_interview.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
{% endblock %}
{% block body %}
<div class="login-box well">
<form action='' method="post">
    Click YES to confirm
    <input type = "submit" value="YES">
    <a href="{{ url_for('helper.show_sets_full') }}">Cancel</a>
</form>
</div>
{% endblock %}

InterviewGenerator/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
    function allowDrop(ev) {
      ev.preventDefault();
    }

    function drag(ev) {
      ev.target.style.opacity = 1;
      ev.dataTransfer.setData("text", ev.target.id);
    }

    function drop(ev) {
      ev.preventDefault();
      var data = ev.dataTransfer.getData("text");
      ev.target.appendChild(document.getElementById(data));
    }
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

	<script type="text/javascript">
		jQuery(document).ready(function($){

	$('.live-search-list h2').each(function(){
	$(this).attr('data-search-term', $(this).text().toLowerCase());
	});

	$('.live-search-box').on('keyup', function(){

	var searchTerm = $(this).val().toLowerCase();
    if ($(this).val() != '') {
		$('.live-search-list h2').each(function(){
              if ($(this).filter('[data-search-term *= ' + searchTerm + ']').length > 0 || searchTerm.length < 1) {
                  $(this).parents('.box--list__item').show();
              } else {
                  $(this).parents('.box--list__item').hide();
              }
		});
    } else {
        $('.live-search-list h2').each(function(){
              $(this).parents('.box--list__item').show();
		});
    }
	});

	});
	</script>
    <title>Quiz App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<!--    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">-->
    <link rel="stylesheet" href="static/common.css">
    <script
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% include 'includes/_navbar.html' %}
    <div class="container">
      {% include 'includes/_messages.html' %}
      {% block body %}{% endblock %}
    </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

InterviewGenerator/templates/register_email.html
<p>You were invited to InterviewGenerator. Please follow this link to activate your account:</p>
<p><a href="{{ token_url }}">{{ token_url }}</a></p>
<br>
<p>Url expires in 45 minutes!</p>